<?php

$provinces = array();
$provinces = array( "Alberta" => "Alberta",
					"British Columbia" => "British Columbia",
					"Labrador" => "Labrador",
					"Manitoba" => "Manitoba",
					"Native Reservations" => "Native Reservations",
					"Nunavut" => "Nunavut",
					"New Brunswick" => "New Brunswick",
					"Newfoundland" => "Newfoundland",
					"North West Territories" => "North West Territories",
					"Nova Scotia" => "Nova Scotia",
					"Ontario" => "Ontario",
					"Prince Edward Island" => "Prince Edward Island",
					"Quebec" => "Quebec",
					"Saskatchewan" => "Saskatchewan",
					"Yukon" => "Yukon");
?>